//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phonebook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phonebook.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate pristup ovom resursu..
        /// </summary>
        public static string Account_AccessDenied_Msg {
            get {
                return ResourceManager.GetString("Account_AccessDenied_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pristup odbijen..
        /// </summary>
        public static string Account_AccessDenied_Title {
            get {
                return ResourceManager.GetString("Account_AccessDenied_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvala vam na potvrti email-a..
        /// </summary>
        public static string Account_ConfirmEmail_Msg {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdite email.
        /// </summary>
        public static string Account_ConfirmEmail_Title {
            get {
                return ResourceManager.GetString("Account_ConfirmEmail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povežite svoj {0} račun..
        /// </summary>
        public static string Account_ExternalLogin_h4 {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste se ovjerili sa.
        /// </summary>
        public static string Account_ExternalLogin_Info {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo da ispod unesite email adresu za ovu stranicu i kliknete  gumb &quot;Registriraj se&quot; za završetak prijave..
        /// </summary>
        public static string Account_ExternalLogin_Info1 {
            get {
                return ResourceManager.GetString("Account_ExternalLogin_Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite svoj email..
        /// </summary>
        public static string Account_ForgotPassword_h4 {
            get {
                return ResourceManager.GetString("Account_ForgotPassword_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaboravili ste lozinku?.
        /// </summary>
        public static string Account_ForgotPassword_Title {
            get {
                return ResourceManager.GetString("Account_ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo da provjerite svoj email kako biste resetirali svoju lozinku..
        /// </summary>
        public static string Account_ForgotPasswordConfirmation_Msg {
            get {
                return ResourceManager.GetString("Account_ForgotPasswordConfirmation_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaboravili ste postavku lozinke.
        /// </summary>
        public static string Account_ForgotPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("Account_ForgotPasswordConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovaj račun je zaključan, pokušajte ponovo kasnije..
        /// </summary>
        public static string Account_Lockout_Msg {
            get {
                return ResourceManager.GetString("Account_Lockout_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izbačen.
        /// </summary>
        public static string Account_Lockout_Title {
            get {
                return ResourceManager.GetString("Account_Lockout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavite se lokalnim računom..
        /// </summary>
        public static string Account_Login_Msg {
            get {
                return ResourceManager.GetString("Account_Login_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrirajte se kao novi korisnik?.
        /// </summary>
        public static string Account_Login_Msg1 {
            get {
                return ResourceManager.GetString("Account_Login_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za prijavu koristite drugu uslugu..
        /// </summary>
        public static string Account_Login_Msg2 {
            get {
                return ResourceManager.GetString("Account_Login_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema konfiguriranih vanjskih usluga provjere autentičnosti. Pogledajte.
        /// </summary>
        public static string Account_Login_Msg3_1 {
            get {
                return ResourceManager.GetString("Account_Login_Msg3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pojedinosti o postavljanju ASP.NET aplikacije da biste podržali prijavu putem vanjskih usluga..
        /// </summary>
        public static string Account_Login_Msg3_2 {
            get {
                return ResourceManager.GetString("Account_Login_Msg3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ovaj članak.
        /// </summary>
        public static string Account_Login_Msg3_Link {
            get {
                return ResourceManager.GetString("Account_Login_Msg3_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} mora biti duga bar {2} znaka i najviše {1}..
        /// </summary>
        public static string Account_LoginWith2fa_Error {
            get {
                return ResourceManager.GetString("Account_LoginWith2fa_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod autentifikatora.
        /// </summary>
        public static string Account_LoginWith2fa_Label {
            get {
                return ResourceManager.GetString("Account_LoginWith2fa_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate pristup vašem uređaju za provjeru autentičnosti? Možete.
        /// </summary>
        public static string Account_LoginWith2fa_Msg1_1 {
            get {
                return ResourceManager.GetString("Account_LoginWith2fa_Msg1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se prijaviti pomoću koda za oporavak.
        /// </summary>
        public static string Account_LoginWith2fa_Msg1_2 {
            get {
                return ResourceManager.GetString("Account_LoginWith2fa_Msg1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamti ovaj stroj.
        /// </summary>
        public static string Account_LoginWith2fa_RememberMachine {
            get {
                return ResourceManager.GetString("Account_LoginWith2fa_RememberMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autentikacija dva čimbenika.
        /// </summary>
        public static string Account_LoginWith2fa_Title {
            get {
                return ResourceManager.GetString("Account_LoginWith2fa_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaša prijava je zaštićena aplikacijom autentifikatora. U nastavku unesite kod autentifikatora..
        /// </summary>
        public static string Account_LoginWith2fa_Title_Msg {
            get {
                return ResourceManager.GetString("Account_LoginWith2fa_Title_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod za oporavak.
        /// </summary>
        public static string Account_LoginWithRecoveryCode_Label {
            get {
                return ResourceManager.GetString("Account_LoginWithRecoveryCode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatražili ste prijavu pomoću koda za oporavak. Ova prijava neće se pamtiti sve dok ne pošaljete
        ///     kod aplikacije autentifikatora pri prijavi ili onemogućite 2FA i ponovno se prijavite..
        /// </summary>
        public static string Account_LoginWithRecoveryCode_Msg {
            get {
                return ResourceManager.GetString("Account_LoginWithRecoveryCode_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda kodova za oporavak.
        /// </summary>
        public static string Account_LoginWithRecoveryCode_Title {
            get {
                return ResourceManager.GetString("Account_LoginWithRecoveryCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi novi račun..
        /// </summary>
        public static string Account_Register_Msg {
            get {
                return ResourceManager.GetString("Account_Register_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija.
        /// </summary>
        public static string Account_Register_Title {
            get {
                return ResourceManager.GetString("Account_Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka i lozinka za potvrdu se ne podudaraju..
        /// </summary>
        public static string Account_ResetPassword_CodeErrorMsg {
            get {
                return ResourceManager.GetString("Account_ResetPassword_CodeErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetiraj svoju lozinku..
        /// </summary>
        public static string Account_ResetPassword_Msg {
            get {
                return ResourceManager.GetString("Account_ResetPassword_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetiraj lozinku.
        /// </summary>
        public static string Account_ResetPassword_Title {
            get {
                return ResourceManager.GetString("Account_ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaša lozinka je restartirana. Molim.
        /// </summary>
        public static string Account_ResetPasswordConfirmation_Msg1_1 {
            get {
                return ResourceManager.GetString("Account_ResetPasswordConfirmation_Msg1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kliknite ovdje za prijavu.
        /// </summary>
        public static string Account_ResetPasswordConfirmation_Msg1_2 {
            get {
                return ResourceManager.GetString("Account_ResetPasswordConfirmation_Msg1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda resetiranja lozinke.
        /// </summary>
        public static string Account_ResetPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("Account_ResetPasswordConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste se odjavili..
        /// </summary>
        public static string Account_SignedOut_Msg {
            get {
                return ResourceManager.GetString("Account_SignedOut_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavljen.
        /// </summary>
        public static string Account_SignedOut_Title {
            get {
                return ResourceManager.GetString("Account_SignedOut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad na popis.
        /// </summary>
        public static string Btn_BackToList {
            get {
                return ResourceManager.GetString("Btn_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        public static string Btn_Details {
            get {
                return ResourceManager.GetString("Btn_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generiraj kodove za oporavak.
        /// </summary>
        public static string Btn_GenerateRecoveryCodes {
            get {
                return ResourceManager.GetString("Btn_GenerateRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni.
        /// </summary>
        public static string Btn_Remove {
            get {
                return ResourceManager.GetString("Btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetiraj.
        /// </summary>
        public static string Btn_Reset {
            get {
                return ResourceManager.GetString("Btn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetiraj ključ za autentifikaciju.
        /// </summary>
        public static string Btn_ResetAuthenticatorKey {
            get {
                return ResourceManager.GetString("Btn_ResetAuthenticatorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetiraj kodove za oporavak.
        /// </summary>
        public static string Btn_ResetRecoveryCodes {
            get {
                return ResourceManager.GetString("Btn_ResetRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pošalji.
        /// </summary>
        public static string Btn_Submit {
            get {
                return ResourceManager.GetString("Btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažuriraj lozinku.
        /// </summary>
        public static string Btn_UpdatePassword {
            get {
                return ResourceManager.GetString("Btn_UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string Btn_Verifiy {
            get {
                return ResourceManager.GetString("Btn_Verifiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novi kontakt.
        /// </summary>
        public static string Create_Title2 {
            get {
                return ResourceManager.GetString("Create_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li sigurno želite obrisati ovo?.
        /// </summary>
        public static string Delete_Msg {
            get {
                return ResourceManager.GetString("Delete_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška..
        /// </summary>
        public static string Error_Error {
            get {
                return ResourceManager.GetString("Error_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogodila se greška tijekom provođenja vašeg zahtijeva..
        /// </summary>
        public static string Error_ErrorMsg {
            get {
                return ResourceManager.GetString("Error_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stvori.
        /// </summary>
        public static string Home_Index_Create {
            get {
                return ResourceManager.GetString("Home_Index_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši sve.
        /// </summary>
        public static string Home_Index_DeleteAll {
            get {
                return ResourceManager.GetString("Home_Index_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traži.
        /// </summary>
        public static string Home_Index_Search {
            get {
                return ResourceManager.GetString("Home_Index_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi lozinku.
        /// </summary>
        public static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova lozinka.
        /// </summary>
        public static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stara lozinka.
        /// </summary>
        public static string Label_OldPassword {
            get {
                return ResourceManager.GetString("Label_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamti me.
        /// </summary>
        public static string Label_RememberMe {
            get {
                return ResourceManager.GetString("Label_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string Label_Username {
            get {
                return ResourceManager.GetString("Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod za potvrdu.
        /// </summary>
        public static string Label_VerificationCode {
            get {
                return ResourceManager.GetString("Label_VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava.
        /// </summary>
        public static string Layout_LogIn {
            get {
                return ResourceManager.GetString("Layout_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjava.
        /// </summary>
        public static string Layout_LogOut {
            get {
                return ResourceManager.GetString("Layout_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imenik.
        /// </summary>
        public static string Layout_Phonebook {
            get {
                return ResourceManager.GetString("Layout_Phonebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracija.
        /// </summary>
        public static string Layout_Register {
            get {
                return ResourceManager.GetString("Layout_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jezik.
        /// </summary>
        public static string Layout_Settings_Header {
            get {
                return ResourceManager.GetString("Layout_Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobrodošli {0}!.
        /// </summary>
        public static string Layout_Welcome {
            get {
                return ResourceManager.GetString("Layout_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijeni lozinku.
        /// </summary>
        public static string Manage_ChangePassword_Title {
            get {
                return ResourceManager.GetString("Manage_ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ova radnja onemogućuje samo 2FA..
        /// </summary>
        public static string Manage_Disable2fa_Msg {
            get {
                return ResourceManager.GetString("Manage_Disable2fa_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onemogućavanje 2FA ne mijenja ključeve koji se koriste u aplikacijama autentifikatora. Ako želite promijeniti ključ koji se koristi u aplikaciji autentifikatora, trebali biste.
        /// </summary>
        public static string Manage_Disable2fa_Msg1_1 {
            get {
                return ResourceManager.GetString("Manage_Disable2fa_Msg1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resetirati ključeve autentifikatora..
        /// </summary>
        public static string Manage_Disable2fa_Msg1_2 {
            get {
                return ResourceManager.GetString("Manage_Disable2fa_Msg1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onemogući 2FA.
        /// </summary>
        public static string Manage_Disable2fa_Msg2 {
            get {
                return ResourceManager.GetString("Manage_Disable2fa_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onemogući provjere autentičnosti s dva faktora (2FA).
        /// </summary>
        public static string Manage_Disable2fa_Title {
            get {
                return ResourceManager.GetString("Manage_Disable2fa_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da biste upotrebljavali aplikaciju za provjeru autentičnosti, prođite kroz sljedeće korake:.
        /// </summary>
        public static string Manage_EnableAuthenticator_Msg {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preuzmite aplikaciju autentifikatora s dva faktora kao što je Microsoft Authenticator.
        /// </summary>
        public static string Manage_EnableAuthenticator_Msg1_1 {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Msg1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google autentifikator za.
        /// </summary>
        public static string Manage_EnableAuthenticator_Msg1_2 {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Msg1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skenirajte QR kod ili unesite ovaj ključ.
        /// </summary>
        public static string Manage_EnableAuthenticator_Msg2_1 {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Msg2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u vašu autentifikaciju za dva faktora. Razmaci i veliko/malo slovo nisu važni..
        /// </summary>
        public static string Manage_EnableAuthenticator_Msg2_2 {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Msg2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da biste omogućili generiranje QR koda, pročitajte naše..
        /// </summary>
        public static string Manage_EnableAuthenticator_Msg2_3 {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Msg2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dokumentaciju.
        /// </summary>
        public static string Manage_EnableAuthenticator_Msg2_4 {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Msg2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakon što skenirate QR kod ili unesete ključ iznad, vaša će aplikacija za provjeru autentičnosti faktora pružiti jedinstveni kod. Unesite kod u okvir za potvrdu u nastavku..
        /// </summary>
        public static string Manage_EnableAuthenticator_Msg3 {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omogući autentifikaciju.
        /// </summary>
        public static string Manage_EnableAuthenticator_Title {
            get {
                return ResourceManager.GetString("Manage_EnableAuthenticator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodajte drugu uskugu za prijavu..
        /// </summary>
        public static string Manage_ExternalLogins_Msg {
            get {
                return ResourceManager.GetString("Manage_ExternalLogins_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljajte vanjskim prijavama.
        /// </summary>
        public static string Manage_ExternalLogins_Title {
            get {
                return ResourceManager.GetString("Manage_ExternalLogins_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ova radnja generira nove kodove za oporavak..
        /// </summary>
        public static string Manage_GenerateRecoveryCodes_Msg {
            get {
                return ResourceManager.GetString("Manage_GenerateRecoveryCodes_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ako izgubite uređaj i nemate kodove oporavka, izgubit ćete pristup računu..
        /// </summary>
        public static string Manage_GenerateRecoveryCodes_Msg1 {
            get {
                return ResourceManager.GetString("Manage_GenerateRecoveryCodes_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generiranje novih kodova za oporavak ne mijenja ključeve koji se upotrebljavaju u aplikacijama za provjeru autentičnosti. Ako želite promijeniti ključ koji se koristi u aplikaciji autentifikatora, trebali biste.
        /// </summary>
        public static string Manage_GenerateRecoveryCodes_Msg2_1 {
            get {
                return ResourceManager.GetString("Manage_GenerateRecoveryCodes_Msg2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resetirati ključeve autentifikatora..
        /// </summary>
        public static string Manage_GenerateRecoveryCodes_Msg2_2 {
            get {
                return ResourceManager.GetString("Manage_GenerateRecoveryCodes_Msg2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generirajte popis kodova za oporavak od dva faktora (2FA).
        /// </summary>
        public static string Manage_GenerateRecoveryCodes_Title {
            get {
                return ResourceManager.GetString("Manage_GenerateRecoveryCodes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pošaljite email za potvrdu.
        /// </summary>
        public static string Manage_Index_Msg {
            get {
                return ResourceManager.GetString("Manage_Index_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Manage_Index_Title {
            get {
                return ResourceManager.GetString("Manage_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljajte svojim računom.
        /// </summary>
        public static string Manage_Layout_Msg {
            get {
                return ResourceManager.GetString("Manage_Layout_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promijenite postavke računa.
        /// </summary>
        public static string Manage_Layout_Msg1 {
            get {
                return ResourceManager.GetString("Manage_Layout_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanjske prijave.
        /// </summary>
        public static string Manage_ManageNav_ExternalLogins {
            get {
                return ResourceManager.GetString("Manage_ManageNav_ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dvo faktorna autentifikacija.
        /// </summary>
        public static string Manage_ManageNav_Msg {
            get {
                return ResourceManager.GetString("Manage_ManageNav_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Manage_ManageNav_Profile {
            get {
                return ResourceManager.GetString("Manage_ManageNav_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ako poništite ključ autentifikatora, aplikacija autentifikatora neće raditi dok ga ne rekonfigurirate..
        /// </summary>
        public static string Manage_ResetAuthenticator_Msg {
            get {
                return ResourceManager.GetString("Manage_ResetAuthenticator_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taj postupak onemogućuje aplikaciju 2FA dok ne potvrdite aplikaciju autentifikatora i vratit ćete i kodove oporavka 2FA. Ako ne dovršite konfiguraciju aplikacije autentifikatora, možete izgubiti pristup računu..
        /// </summary>
        public static string Manage_ResetAuthenticator_Msg1 {
            get {
                return ResourceManager.GetString("Manage_ResetAuthenticator_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetiraj ključ autentifikatora.
        /// </summary>
        public static string Manage_ResetAuthenticator_Title {
            get {
                return ResourceManager.GetString("Manage_ResetAuthenticator_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate lokalno korisničko ime / zaporku za ovu web stranicu. Dodajte lokalni račun kako biste se mogli prijaviti bez vanjske prijave..
        /// </summary>
        public static string Manage_SetPassword_Msg {
            get {
                return ResourceManager.GetString("Manage_SetPassword_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavi lozinku.
        /// </summary>
        public static string Manage_SetPassword_Title {
            get {
                return ResourceManager.GetString("Manage_SetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stavite ove kodove na sigurno mjesto..
        /// </summary>
        public static string Manage_ShowRecoveryCodes_Msg {
            get {
                return ResourceManager.GetString("Manage_ShowRecoveryCodes_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ako izgubite uređaj i nemate kodove oporavka, izgubit ćete pristup računu..
        /// </summary>
        public static string Manage_ShowRecoveryCodes_Msg1 {
            get {
                return ResourceManager.GetString("Manage_ShowRecoveryCodes_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodovi za oporavak.
        /// </summary>
        public static string Manage_ShowRecoveryCodes_Title {
            get {
                return ResourceManager.GetString("Manage_ShowRecoveryCodes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate preostalih kodova za oporavak..
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Msg {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morate.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Msg1_1 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Msg1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generirati novi skup kodova za oporavak.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Msg1_2 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Msg1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prije nego što se možete prijaviti kodom za oporavak..
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Msg1_3 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Msg1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imate još 1 kod za oporavak..
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Msg2_1 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Msg2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Možete.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Msg2_2 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Msg2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preostalo vam je {0} kodova za oporavak..
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Msg3_1 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Msg3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trebate.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Msg3_2 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Msg3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj aplikaciju za autnetifikaciju.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Msg4 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguriranje aplikacije autentifikatora.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Msg5 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetiraj ključ autentifikatora.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Msg6 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenitifikatorska aplikacija.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Msg7 {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dvo faktorna autentifikacija.
        /// </summary>
        public static string Manage_TwoFactorAuthentication_Title {
            get {
                return ResourceManager.GetString("Manage_TwoFactorAuthentication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string Model_NewContact__LastName {
            get {
                return ResourceManager.GetString("Model_NewContact__LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string Model_NewContact_City {
            get {
                return ResourceManager.GetString("Model_NewContact_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država.
        /// </summary>
        public static string Model_NewContact_Country {
            get {
                return ResourceManager.GetString("Model_NewContact_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Model_NewContact_Email {
            get {
                return ResourceManager.GetString("Model_NewContact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string Model_NewContact_FirstName {
            get {
                return ResourceManager.GetString("Model_NewContact_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona.
        /// </summary>
        public static string Model_NewContact_PhoneNumber {
            get {
                return ResourceManager.GetString("Model_NewContact_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poštanski broj.
        /// </summary>
        public static string Model_NewContact_PostalCode {
            get {
                return ResourceManager.GetString("Model_NewContact_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        public static string Model_NewContact_Street {
            get {
                return ResourceManager.GetString("Model_NewContact_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string Text_and {
            get {
                return ResourceManager.GetString("Text_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string Text_Android {
            get {
                return ResourceManager.GetString("Text_Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS.
        /// </summary>
        public static string Text_iOS {
            get {
                return ResourceManager.GetString("Text_iOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Text_or {
            get {
                return ResourceManager.GetString("Text_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsPhone.
        /// </summary>
        public static string Text_WindowsPhone {
            get {
                return ResourceManager.GetString("Text_WindowsPhone", resourceCulture);
            }
        }
    }
}
